import type { AppProps } from 'next/app'
import Head from 'next/head';
import { Provider } from 'react-redux';
import { store } from 'store';

import themingWrapper from '@helpers/themingHelper';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Tammana Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        {themingWrapper(<Component {...pageProps} />)}
      </Provider>
    </>
  )
}

export default MyApp
