import type { NextPage } from 'next'
import Head from 'next/head'

import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '@styles/sharedStyles';

import WeatherDisplay from '@features/weatherDisplay/WeatherDisplay';

const Home: NextPage = () => {

  return (
    <Container>
      <Head>
        <title>Tammana Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>Tammana Weather app</Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>
        <WeatherDisplay />
      </Main>
    </Container>
  )
}

export default Home
